import { CaseRecord } from "./types";

export const DEMO_DATA: CaseRecord[] = [
  {
    cod_pre: 1001,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "Las Playas",
    sexo_: "M",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-15"
  },
  {
    cod_pre: 1002,
    semana: 20,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Alfonso Lopez",
    sexo_: "F",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-16"
  },
  {
    cod_pre: 1003,
    semana: 20,
    año: 2026,
    esp_ani: 4,
    clasificacion_exposicion: 0,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "Naranjal",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-17"
  },
  {
    cod_pre: 1004,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "El Diamante",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 2,
    fec_not: "2026-05-18"
  },
  {
    cod_pre: 1005,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Prada",
    rep_se_ant: "si", // EXCLUDE THIS
    localidad_: "BELEN",
    bar_ver_: "Fátima",
    sexo_: "F",
    clas_post_seg: "Excluido - Previo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-15"
  },
  {
    cod_pre: 1006,
    semana: 21,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Aures",
    sexo_: "M",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-22"
  },
  {
    cod_pre: 1007,
    semana: 21,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "La Gloria",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-23"
  },
  {
    cod_pre: 1008,
    semana: 21,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 0,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Tricentenario",
    sexo_: "F",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 3,
    fec_not: "2026-05-24"
  },
  {
    cod_pre: 1009,
    semana: 21,
    año: 2026,
    esp_ani: 4,
    clasificacion_exposicion: 2,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "Florida Nueva",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 2,
    fec_not: "2026-05-25"
  },
  {
    cod_pre: 1010,
    semana: 21,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Miramar",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-26"
  },
  {
    cod_pre: 1011,
    semana: 22,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "Loma de los Bernal",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-29"
  },
  {
    cod_pre: 1012,
    semana: 22,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 0,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Castilla",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-30"
  },
  {
    cod_pre: 1013,
    semana: 22,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "San Joaquin",
    sexo_: "M",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-31"
  },
  {
    cod_pre: 1014,
    semana: 22,
    año: 2026,
    esp_ani: 4,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Villa Flora",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 2,
    fec_not: "2026-06-01"
  },
  {
    cod_pre: 1015,
    semana: 22,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "SI ", // EXCLUDE THIS
    localidad_: "LAURELES",
    bar_ver_: "La Castellana",
    sexo_: "M",
    clas_post_seg: "Excluido - Previo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-29"
  },
  {
    cod_pre: 1016,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Gracia",
    sexo_: "F",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-15"
  },
  {
    cod_pre: 1017,
    semana: 20,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "San Bernardo",
    sexo_: "M",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-16"
  },
  {
    cod_pre: 1018,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 0,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "Lorena",
    sexo_: "M",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-17"
  },
  {
    cod_pre: 1019,
    semana: 20,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Pajarito",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-18"
  },
  {
    cod_pre: 1020,
    semana: 20,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "El Rincón",
    sexo_: "F",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-19"
  },
  {
    cod_pre: 1021,
    semana: 21,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Kennedy",
    sexo_: "M",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-22"
  },
  {
    cod_pre: 1022,
    semana: 21,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Boyacá",
    sexo_: "F",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-23"
  },
  {
    cod_pre: 1023,
    semana: 21,
    año: 2026,
    esp_ani: 4,
    clasificacion_exposicion: 0,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "Las Acacias",
    sexo_: "M",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-24"
  },
  {
    cod_pre: 1024,
    semana: 21,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "La Palma",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 3,
    fec_not: "2026-05-25"
  },
  {
    cod_pre: 1025,
    semana: 21,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "Palenque",
    sexo_: "F",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-26"
  },
  {
    cod_pre: 1026,
    semana: 22,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "LAURELES",
    bar_ver_: "Conquistadores",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-05-29"
  },
  {
    cod_pre: 1027,
    semana: 22,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "Altavista",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-30"
  },
  {
    cod_pre: 1028,
    semana: 22,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 0,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Pedregal",
    sexo_: "M",
    clas_post_seg: "Cerrado - Negativo",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-05-31"
  },
  {
    cod_pre: 1029,
    semana: 22,
    año: 2026,
    esp_ani: 4,
    clasificacion_exposicion: 2,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "La Pilarica",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-06-01"
  },
  {
    cod_pre: 1030,
    semana: 22,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "BELEN",
    bar_ver_: "Miravalle",
    sexo_: "M",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-06-02"
  },
  {
    cod_pre: 1031,
    semana: 22,
    año: 2026,
    esp_ani: 1,
    clasificacion_exposicion: 2,
    responsable: "Prada",
    rep_se_ant: "no",
    localidad_: "CASTILLA",
    bar_ver_: "Las Brisas",
    sexo_: "F",
    clas_post_seg: "Cerrado - Vacunado",
    seg_prioritario: "Si",
    estado_ani: 1,
    fec_not: "2026-06-03"
  },
  {
    cod_pre: 1032,
    semana: 22,
    año: 2026,
    esp_ani: 2,
    clasificacion_exposicion: 1,
    responsable: "Juan",
    rep_se_ant: "no",
    localidad_: "ROBLEDO",
    bar_ver_: "El Volador",
    sexo_: "M",
    clas_post_seg: "En proceso",
    seg_prioritario: "No",
    estado_ani: 1,
    fec_not: "2026-06-04"
  }
];
